// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package store

import (
	"context"
)

const createFeedItem = `-- name: CreateFeedItem :exec
INSERT INTO feed_items (
    id,
    source_id,
    external_id,
    title,
    url,
    author,
    summary,
    thumbnail_url,
    published_at,
    saved,
    read,
    created_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, datetime('now'))
`

type CreateFeedItemParams struct {
	ID           string `json:"id"`
	SourceID     string `json:"source_id"`
	ExternalID   string `json:"external_id"`
	Title        string `json:"title"`
	Url          string `json:"url"`
	Author       string `json:"author"`
	Summary      string `json:"summary"`
	ThumbnailUrl string `json:"thumbnail_url"`
	PublishedAt  string `json:"published_at"`
	Saved        int64  `json:"saved"`
}

func (q *Queries) CreateFeedItem(ctx context.Context, arg CreateFeedItemParams) error {
	_, err := q.db.ExecContext(ctx, createFeedItem,
		arg.ID,
		arg.SourceID,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Author,
		arg.Summary,
		arg.ThumbnailUrl,
		arg.PublishedAt,
		arg.Saved,
	)
	return err
}

const createFeedSource = `-- name: CreateFeedSource :exec
INSERT INTO feed_sources (
    id,
    kind,
    title,
    url,
    remote_id,
    enabled,
    last_error,
    last_fetched_at,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, 1, '', '', datetime('now'), datetime('now'))
`

type CreateFeedSourceParams struct {
	ID       string `json:"id"`
	Kind     string `json:"kind"`
	Title    string `json:"title"`
	Url      string `json:"url"`
	RemoteID string `json:"remote_id"`
}

func (q *Queries) CreateFeedSource(ctx context.Context, arg CreateFeedSourceParams) error {
	_, err := q.db.ExecContext(ctx, createFeedSource,
		arg.ID,
		arg.Kind,
		arg.Title,
		arg.Url,
		arg.RemoteID,
	)
	return err
}

const deleteFeedItem = `-- name: DeleteFeedItem :exec
DELETE FROM feed_items
WHERE id = ?
`

func (q *Queries) DeleteFeedItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFeedItem, id)
	return err
}

const deleteFeedSource = `-- name: DeleteFeedSource :exec
DELETE FROM feed_sources
WHERE id = ?
`

func (q *Queries) DeleteFeedSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFeedSource, id)
	return err
}

const getFeedItem = `-- name: GetFeedItem :one
SELECT
    id,
    source_id,
    external_id,
    title,
    url,
    author,
    summary,
    thumbnail_url,
    published_at,
    saved,
    read,
    created_at
FROM feed_items
WHERE id = ?
`

func (q *Queries) GetFeedItem(ctx context.Context, id string) (FeedItem, error) {
	row := q.db.QueryRowContext(ctx, getFeedItem, id)
	var i FeedItem
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.Summary,
		&i.ThumbnailUrl,
		&i.PublishedAt,
		&i.Saved,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedItemBySourceExternal = `-- name: GetFeedItemBySourceExternal :one
SELECT
    id,
    source_id,
    external_id,
    title,
    url,
    author,
    summary,
    thumbnail_url,
    published_at,
    saved,
    read,
    created_at
FROM feed_items
WHERE source_id = ?
    AND external_id = ?
`

type GetFeedItemBySourceExternalParams struct {
	SourceID   string `json:"source_id"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetFeedItemBySourceExternal(ctx context.Context, arg GetFeedItemBySourceExternalParams) (FeedItem, error) {
	row := q.db.QueryRowContext(ctx, getFeedItemBySourceExternal, arg.SourceID, arg.ExternalID)
	var i FeedItem
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Author,
		&i.Summary,
		&i.ThumbnailUrl,
		&i.PublishedAt,
		&i.Saved,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedSource = `-- name: GetFeedSource :one
SELECT
    id,
    kind,
    title,
    url,
    remote_id,
    enabled,
    last_error,
    last_fetched_at,
    created_at,
    updated_at
FROM feed_sources
WHERE id = ?
`

func (q *Queries) GetFeedSource(ctx context.Context, id string) (FeedSource, error) {
	row := q.db.QueryRowContext(ctx, getFeedSource, id)
	var i FeedSource
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Url,
		&i.RemoteID,
		&i.Enabled,
		&i.LastError,
		&i.LastFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeedItems = `-- name: ListFeedItems :many
SELECT
    i.id,
    i.source_id,
    i.external_id,
    i.title,
    i.url,
    i.author,
    i.summary,
    i.thumbnail_url,
    i.published_at,
    i.saved,
    i.read,
    i.created_at,
    s.kind AS source_kind,
    s.title AS source_title
FROM feed_items i
INNER JOIN feed_sources s ON s.id = i.source_id
ORDER BY
    CASE WHEN i.published_at = '' THEN i.created_at ELSE i.published_at END DESC,
    i.id DESC
LIMIT 300
`

type ListFeedItemsRow struct {
	ID           string `json:"id"`
	SourceID     string `json:"source_id"`
	ExternalID   string `json:"external_id"`
	Title        string `json:"title"`
	Url          string `json:"url"`
	Author       string `json:"author"`
	Summary      string `json:"summary"`
	ThumbnailUrl string `json:"thumbnail_url"`
	PublishedAt  string `json:"published_at"`
	Saved        int64  `json:"saved"`
	Read         int64  `json:"read"`
	CreatedAt    string `json:"created_at"`
	SourceKind   string `json:"source_kind"`
	SourceTitle  string `json:"source_title"`
}

func (q *Queries) ListFeedItems(ctx context.Context) ([]ListFeedItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedItemsRow{}
	for rows.Next() {
		var i ListFeedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Summary,
			&i.ThumbnailUrl,
			&i.PublishedAt,
			&i.Saved,
			&i.Read,
			&i.CreatedAt,
			&i.SourceKind,
			&i.SourceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedItemsByKind = `-- name: ListFeedItemsByKind :many
SELECT
    i.id,
    i.source_id,
    i.external_id,
    i.title,
    i.url,
    i.author,
    i.summary,
    i.thumbnail_url,
    i.published_at,
    i.saved,
    i.read,
    i.created_at,
    s.kind AS source_kind,
    s.title AS source_title
FROM feed_items i
INNER JOIN feed_sources s ON s.id = i.source_id
WHERE s.kind = ?
ORDER BY
    CASE WHEN i.published_at = '' THEN i.created_at ELSE i.published_at END DESC,
    i.id DESC
LIMIT 300
`

type ListFeedItemsByKindRow struct {
	ID           string `json:"id"`
	SourceID     string `json:"source_id"`
	ExternalID   string `json:"external_id"`
	Title        string `json:"title"`
	Url          string `json:"url"`
	Author       string `json:"author"`
	Summary      string `json:"summary"`
	ThumbnailUrl string `json:"thumbnail_url"`
	PublishedAt  string `json:"published_at"`
	Saved        int64  `json:"saved"`
	Read         int64  `json:"read"`
	CreatedAt    string `json:"created_at"`
	SourceKind   string `json:"source_kind"`
	SourceTitle  string `json:"source_title"`
}

func (q *Queries) ListFeedItemsByKind(ctx context.Context, kind string) ([]ListFeedItemsByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedItemsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedItemsByKindRow{}
	for rows.Next() {
		var i ListFeedItemsByKindRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Summary,
			&i.ThumbnailUrl,
			&i.PublishedAt,
			&i.Saved,
			&i.Read,
			&i.CreatedAt,
			&i.SourceKind,
			&i.SourceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedSources = `-- name: ListFeedSources :many
SELECT
    id,
    kind,
    title,
    url,
    remote_id,
    enabled,
    last_error,
    last_fetched_at,
    created_at,
    updated_at
FROM feed_sources
ORDER BY kind ASC, title ASC
`

func (q *Queries) ListFeedSources(ctx context.Context) ([]FeedSource, error) {
	rows, err := q.db.QueryContext(ctx, listFeedSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedSource{}
	for rows.Next() {
		var i FeedSource
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Title,
			&i.Url,
			&i.RemoteID,
			&i.Enabled,
			&i.LastError,
			&i.LastFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedFeedItems = `-- name: ListSavedFeedItems :many
SELECT
    i.id,
    i.source_id,
    i.external_id,
    i.title,
    i.url,
    i.author,
    i.summary,
    i.thumbnail_url,
    i.published_at,
    i.saved,
    i.read,
    i.created_at,
    s.kind AS source_kind,
    s.title AS source_title
FROM feed_items i
INNER JOIN feed_sources s ON s.id = i.source_id
WHERE i.saved = 1
ORDER BY
    CASE WHEN i.published_at = '' THEN i.created_at ELSE i.published_at END DESC,
    i.id DESC
LIMIT 300
`

type ListSavedFeedItemsRow struct {
	ID           string `json:"id"`
	SourceID     string `json:"source_id"`
	ExternalID   string `json:"external_id"`
	Title        string `json:"title"`
	Url          string `json:"url"`
	Author       string `json:"author"`
	Summary      string `json:"summary"`
	ThumbnailUrl string `json:"thumbnail_url"`
	PublishedAt  string `json:"published_at"`
	Saved        int64  `json:"saved"`
	Read         int64  `json:"read"`
	CreatedAt    string `json:"created_at"`
	SourceKind   string `json:"source_kind"`
	SourceTitle  string `json:"source_title"`
}

func (q *Queries) ListSavedFeedItems(ctx context.Context) ([]ListSavedFeedItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSavedFeedItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedFeedItemsRow{}
	for rows.Next() {
		var i ListSavedFeedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Author,
			&i.Summary,
			&i.ThumbnailUrl,
			&i.PublishedAt,
			&i.Saved,
			&i.Read,
			&i.CreatedAt,
			&i.SourceKind,
			&i.SourceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedItemRead = `-- name: SetFeedItemRead :exec
UPDATE feed_items
SET read = ?
WHERE id = ?
`

type SetFeedItemReadParams struct {
	Read int64  `json:"read"`
	ID   string `json:"id"`
}

func (q *Queries) SetFeedItemRead(ctx context.Context, arg SetFeedItemReadParams) error {
	_, err := q.db.ExecContext(ctx, setFeedItemRead, arg.Read, arg.ID)
	return err
}

const setFeedItemSaved = `-- name: SetFeedItemSaved :exec
UPDATE feed_items
SET saved = ?
WHERE id = ?
`

type SetFeedItemSavedParams struct {
	Saved int64  `json:"saved"`
	ID    string `json:"id"`
}

func (q *Queries) SetFeedItemSaved(ctx context.Context, arg SetFeedItemSavedParams) error {
	_, err := q.db.ExecContext(ctx, setFeedItemSaved, arg.Saved, arg.ID)
	return err
}

const updateFeedItemMetadata = `-- name: UpdateFeedItemMetadata :exec
UPDATE feed_items
SET
    title = ?,
    url = ?,
    author = ?,
    summary = ?,
    thumbnail_url = ?,
    published_at = ?
WHERE id = ?
`

type UpdateFeedItemMetadataParams struct {
	Title        string `json:"title"`
	Url          string `json:"url"`
	Author       string `json:"author"`
	Summary      string `json:"summary"`
	ThumbnailUrl string `json:"thumbnail_url"`
	PublishedAt  string `json:"published_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateFeedItemMetadata(ctx context.Context, arg UpdateFeedItemMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedItemMetadata,
		arg.Title,
		arg.Url,
		arg.Author,
		arg.Summary,
		arg.ThumbnailUrl,
		arg.PublishedAt,
		arg.ID,
	)
	return err
}

const updateFeedSourceFetch = `-- name: UpdateFeedSourceFetch :exec
UPDATE feed_sources
SET
    title = ?,
    last_error = ?,
    last_fetched_at = datetime('now'),
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateFeedSourceFetchParams struct {
	Title     string `json:"title"`
	LastError string `json:"last_error"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateFeedSourceFetch(ctx context.Context, arg UpdateFeedSourceFetchParams) error {
	_, err := q.db.ExecContext(ctx, updateFeedSourceFetch, arg.Title, arg.LastError, arg.ID)
	return err
}
