// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package store

import (
	"context"
	"database/sql"
)

const createAnkiImport = `-- name: CreateAnkiImport :exec
INSERT INTO anki_imports (id, filename, imported_at, status, error_message, stats_json)
VALUES (?, ?, datetime('now'), ?, ?, ?)
`

type CreateAnkiImportParams struct {
	ID           string `json:"id"`
	Filename     string `json:"filename"`
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	StatsJson    string `json:"stats_json"`
}

func (q *Queries) CreateAnkiImport(ctx context.Context, arg CreateAnkiImportParams) error {
	_, err := q.db.ExecContext(ctx, createAnkiImport,
		arg.ID,
		arg.Filename,
		arg.Status,
		arg.ErrorMessage,
		arg.StatsJson,
	)
	return err
}

const createAnkiImportDeck = `-- name: CreateAnkiImportDeck :exec
INSERT INTO anki_import_decks (
    import_id, anki_deck_id, anki_deck_name, target_type, anki_model_id, field_mapping, app_deck_id
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAnkiImportDeckParams struct {
	ImportID     string         `json:"import_id"`
	AnkiDeckID   int64          `json:"anki_deck_id"`
	AnkiDeckName string         `json:"anki_deck_name"`
	TargetType   string         `json:"target_type"`
	AnkiModelID  sql.NullInt64  `json:"anki_model_id"`
	FieldMapping string         `json:"field_mapping"`
	AppDeckID    sql.NullString `json:"app_deck_id"`
}

func (q *Queries) CreateAnkiImportDeck(ctx context.Context, arg CreateAnkiImportDeckParams) error {
	_, err := q.db.ExecContext(ctx, createAnkiImportDeck,
		arg.ImportID,
		arg.AnkiDeckID,
		arg.AnkiDeckName,
		arg.TargetType,
		arg.AnkiModelID,
		arg.FieldMapping,
		arg.AppDeckID,
	)
	return err
}

const getAnkiImport = `-- name: GetAnkiImport :one
SELECT id, filename, imported_at, status, error_message, stats_json
FROM anki_imports
WHERE id = ?
`

func (q *Queries) GetAnkiImport(ctx context.Context, id string) (AnkiImport, error) {
	row := q.db.QueryRowContext(ctx, getAnkiImport, id)
	var i AnkiImport
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.ImportedAt,
		&i.Status,
		&i.ErrorMessage,
		&i.StatsJson,
	)
	return i, err
}

const getAnkiImportDeck = `-- name: GetAnkiImportDeck :one
SELECT import_id, anki_deck_id, anki_deck_name, target_type, anki_model_id, field_mapping, app_deck_id
FROM anki_import_decks
WHERE import_id = ? AND anki_deck_id = ?
`

type GetAnkiImportDeckParams struct {
	ImportID   string `json:"import_id"`
	AnkiDeckID int64  `json:"anki_deck_id"`
}

func (q *Queries) GetAnkiImportDeck(ctx context.Context, arg GetAnkiImportDeckParams) (AnkiImportDeck, error) {
	row := q.db.QueryRowContext(ctx, getAnkiImportDeck, arg.ImportID, arg.AnkiDeckID)
	var i AnkiImportDeck
	err := row.Scan(
		&i.ImportID,
		&i.AnkiDeckID,
		&i.AnkiDeckName,
		&i.TargetType,
		&i.AnkiModelID,
		&i.FieldMapping,
		&i.AppDeckID,
	)
	return i, err
}

const listAnkiImportDecks = `-- name: ListAnkiImportDecks :many
SELECT import_id, anki_deck_id, anki_deck_name, target_type, anki_model_id, field_mapping, app_deck_id
FROM anki_import_decks
WHERE import_id = ?
ORDER BY anki_deck_name
`

func (q *Queries) ListAnkiImportDecks(ctx context.Context, importID string) ([]AnkiImportDeck, error) {
	rows, err := q.db.QueryContext(ctx, listAnkiImportDecks, importID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnkiImportDeck{}
	for rows.Next() {
		var i AnkiImportDeck
		if err := rows.Scan(
			&i.ImportID,
			&i.AnkiDeckID,
			&i.AnkiDeckName,
			&i.TargetType,
			&i.AnkiModelID,
			&i.FieldMapping,
			&i.AppDeckID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnkiImports = `-- name: ListAnkiImports :many
SELECT id, filename, imported_at, status, error_message, stats_json
FROM anki_imports
ORDER BY imported_at DESC
`

func (q *Queries) ListAnkiImports(ctx context.Context) ([]AnkiImport, error) {
	rows, err := q.db.QueryContext(ctx, listAnkiImports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnkiImport{}
	for rows.Next() {
		var i AnkiImport
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.ImportedAt,
			&i.Status,
			&i.ErrorMessage,
			&i.StatsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnkiImportStatus = `-- name: UpdateAnkiImportStatus :exec
UPDATE anki_imports
SET status = ?, error_message = ?, stats_json = ?
WHERE id = ?
`

type UpdateAnkiImportStatusParams struct {
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	StatsJson    string `json:"stats_json"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateAnkiImportStatus(ctx context.Context, arg UpdateAnkiImportStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAnkiImportStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.StatsJson,
		arg.ID,
	)
	return err
}
