// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sudoku.sql

package store

import (
	"context"
)

const createSudokuGame = `-- name: CreateSudokuGame :exec
INSERT INTO sudoku_games (
    id,
    session_id,
    difficulty,
    puzzle,
    solution,
    board,
    status,
    created_at,
    updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type CreateSudokuGameParams struct {
	ID         string `json:"id"`
	SessionID  string `json:"session_id"`
	Difficulty string `json:"difficulty"`
	Puzzle     string `json:"puzzle"`
	Solution   string `json:"solution"`
	Board      string `json:"board"`
	Status     string `json:"status"`
}

func (q *Queries) CreateSudokuGame(ctx context.Context, arg CreateSudokuGameParams) error {
	_, err := q.db.ExecContext(ctx, createSudokuGame,
		arg.ID,
		arg.SessionID,
		arg.Difficulty,
		arg.Puzzle,
		arg.Solution,
		arg.Board,
		arg.Status,
	)
	return err
}

const getSudokuGameBySessionID = `-- name: GetSudokuGameBySessionID :one
SELECT id, session_id, difficulty, puzzle, solution, board, status, created_at, updated_at
FROM sudoku_games
WHERE session_id = ?
`

func (q *Queries) GetSudokuGameBySessionID(ctx context.Context, sessionID string) (SudokuGame, error) {
	row := q.db.QueryRowContext(ctx, getSudokuGameBySessionID, sessionID)
	var i SudokuGame
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Difficulty,
		&i.Puzzle,
		&i.Solution,
		&i.Board,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceSudokuPuzzle = `-- name: ReplaceSudokuPuzzle :exec
UPDATE sudoku_games
SET difficulty = ?,
    puzzle = ?,
    solution = ?,
    board = ?,
    status = 'playing',
    updated_at = datetime('now')
WHERE session_id = ?
`

type ReplaceSudokuPuzzleParams struct {
	Difficulty string `json:"difficulty"`
	Puzzle     string `json:"puzzle"`
	Solution   string `json:"solution"`
	Board      string `json:"board"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) ReplaceSudokuPuzzle(ctx context.Context, arg ReplaceSudokuPuzzleParams) error {
	_, err := q.db.ExecContext(ctx, replaceSudokuPuzzle,
		arg.Difficulty,
		arg.Puzzle,
		arg.Solution,
		arg.Board,
		arg.SessionID,
	)
	return err
}

const updateSudokuGameBoard = `-- name: UpdateSudokuGameBoard :exec
UPDATE sudoku_games
SET board = ?, status = ?, updated_at = datetime('now')
WHERE session_id = ?
`

type UpdateSudokuGameBoardParams struct {
	Board     string `json:"board"`
	Status    string `json:"status"`
	SessionID string `json:"session_id"`
}

func (q *Queries) UpdateSudokuGameBoard(ctx context.Context, arg UpdateSudokuGameBoardParams) error {
	_, err := q.db.ExecContext(ctx, updateSudokuGameBoard, arg.Board, arg.Status, arg.SessionID)
	return err
}
