import { useCallback, useEffect, useRef } from 'react';
import { Box, ScrollArea, Stack, Text, Title } from '@mantine/core';
import { ChatBubble } from '../ChatBubble';
import classes from './ChatThread.module.css';

/**
 * Represents a chat message in the thread.
 */
export interface ChatMessageItem {
  id: string;
  session_id: string;
  role: 'user' | 'assistant';
  content: string;
  created_at: string;
  /** Indicates if the message is currently being generated by the assistant */
  generating?: boolean;
}

/**
 * Props for the ChatThread component.
 */
interface ChatThreadProps {
  /** Array of messages to display in chronological order */
  messages: ChatMessageItem[];
  /** Title of the current chat session */
  sessionTitle: string | null;
  /** Whether a session is currently active */
  hasActiveSession: boolean;
}

/**
 * ChatThread displays the conversation history for the active chat session.
 * It automatically scrolls to the bottom when new messages arrive and shows
 * an empty state when no messages exist yet.
 */

export function ChatThread({ messages, sessionTitle, hasActiveSession }: ChatThreadProps) {
  const viewportRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = useCallback(() => {
    if (viewportRef.current) {
      viewportRef.current.scrollTop = viewportRef.current.scrollHeight;
    }
  }, []);

  useEffect(() => {
    scrollToBottom();
  }, [messages, scrollToBottom]);

  if (!hasActiveSession) {
    return null;
  }

  return (
    <Box className={classes.thread}>
      <Box className={classes.header}>
        <Title order={4}>{sessionTitle ?? 'Chat'}</Title>
      </Box>

      <ScrollArea className={classes.scrollArea} viewportRef={viewportRef} type="auto">
        {messages.length === 0 ? (
          <Box className={classes.emptyThread}>
            <Text c="dimmed" size="sm">
              Send a message to begin this conversation.
            </Text>
          </Box>
        ) : (
          <Stack gap="xs" className={classes.messageList}>
            {messages.map((message) => (
              <ChatBubble
                key={message.id}
                role={message.role}
                content={message.content}
                streaming={message.generating}
              />
            ))}
          </Stack>
        )}
      </ScrollArea>
    </Box>
  );
}
