// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: articles.sql

package store

import (
	"context"
	"database/sql"
)

const countArticles = `-- name: CountArticles :one
SELECT count(*) FROM articles
`

func (q *Queries) CountArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :exec
INSERT INTO articles (
    id, title, url, content, translation, level, source, word_count,
    anki_note_guid, model_css, raw_fields, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type CreateArticleParams struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Url          string         `json:"url"`
	Content      string         `json:"content"`
	Translation  string         `json:"translation"`
	Level        string         `json:"level"`
	Source       string         `json:"source"`
	WordCount    int64          `json:"word_count"`
	AnkiNoteGuid sql.NullString `json:"anki_note_guid"`
	ModelCss     string         `json:"model_css"`
	RawFields    string         `json:"raw_fields"`
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) error {
	_, err := q.db.ExecContext(ctx, createArticle,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Content,
		arg.Translation,
		arg.Level,
		arg.Source,
		arg.WordCount,
		arg.AnkiNoteGuid,
		arg.ModelCss,
		arg.RawFields,
	)
	return err
}

const createClipping = `-- name: CreateClipping :exec
INSERT INTO clippings (id, article_id, text, translation, explanation, note, saved_to_card, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateClippingParams struct {
	ID          string         `json:"id"`
	ArticleID   sql.NullString `json:"article_id"`
	Text        string         `json:"text"`
	Translation string         `json:"translation"`
	Explanation string         `json:"explanation"`
	Note        string         `json:"note"`
	SavedToCard int64          `json:"saved_to_card"`
}

func (q *Queries) CreateClipping(ctx context.Context, arg CreateClippingParams) error {
	_, err := q.db.ExecContext(ctx, createClipping,
		arg.ID,
		arg.ArticleID,
		arg.Text,
		arg.Translation,
		arg.Explanation,
		arg.Note,
		arg.SavedToCard,
	)
	return err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles
WHERE id = ?
`

func (q *Queries) DeleteArticle(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const deleteClipping = `-- name: DeleteClipping :exec
DELETE FROM clippings
WHERE id = ?
`

func (q *Queries) DeleteClipping(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteClipping, id)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT
    id, title, url, content, translation, level, source, word_count,
    anki_note_guid, model_css, raw_fields, created_at, updated_at
FROM articles
WHERE id = ?
`

func (q *Queries) GetArticle(ctx context.Context, id string) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Content,
		&i.Translation,
		&i.Level,
		&i.Source,
		&i.WordCount,
		&i.AnkiNoteGuid,
		&i.ModelCss,
		&i.RawFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getArticleByAnkiNoteGuid = `-- name: GetArticleByAnkiNoteGuid :one
SELECT
    id, title, url, content, translation, level, source, word_count,
    anki_note_guid, model_css, raw_fields, created_at, updated_at
FROM articles
WHERE anki_note_guid = ?
`

func (q *Queries) GetArticleByAnkiNoteGuid(ctx context.Context, ankiNoteGuid sql.NullString) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleByAnkiNoteGuid, ankiNoteGuid)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.Content,
		&i.Translation,
		&i.Level,
		&i.Source,
		&i.WordCount,
		&i.AnkiNoteGuid,
		&i.ModelCss,
		&i.RawFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClipping = `-- name: GetClipping :one
SELECT id, article_id, text, translation, explanation, note, saved_to_card, created_at
FROM clippings
WHERE id = ?
`

func (q *Queries) GetClipping(ctx context.Context, id string) (Clipping, error) {
	row := q.db.QueryRowContext(ctx, getClipping, id)
	var i Clipping
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.Text,
		&i.Translation,
		&i.Explanation,
		&i.Note,
		&i.SavedToCard,
		&i.CreatedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT
    id, title, url, content, translation, level, source, word_count,
    anki_note_guid, model_css, raw_fields, created_at, updated_at
FROM articles
ORDER BY created_at DESC
`

func (q *Queries) ListArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Translation,
			&i.Level,
			&i.Source,
			&i.WordCount,
			&i.AnkiNoteGuid,
			&i.ModelCss,
			&i.RawFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesBySource = `-- name: ListArticlesBySource :many
SELECT
    id, title, url, content, translation, level, source, word_count,
    anki_note_guid, model_css, raw_fields, created_at, updated_at
FROM articles
WHERE source = ?
ORDER BY created_at DESC
`

func (q *Queries) ListArticlesBySource(ctx context.Context, source string) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesBySource, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Content,
			&i.Translation,
			&i.Level,
			&i.Source,
			&i.WordCount,
			&i.AnkiNoteGuid,
			&i.ModelCss,
			&i.RawFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticlesPage = `-- name: ListArticlesPage :many
SELECT id, title, source, word_count, created_at
FROM articles
ORDER BY created_at DESC
LIMIT ?
OFFSET ?
`

type ListArticlesPageParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListArticlesPageRow struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Source    string `json:"source"`
	WordCount int64  `json:"word_count"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) ListArticlesPage(ctx context.Context, arg ListArticlesPageParams) ([]ListArticlesPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listArticlesPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticlesPageRow{}
	for rows.Next() {
		var i ListArticlesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.WordCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClippingsByArticle = `-- name: ListClippingsByArticle :many
SELECT id, article_id, text, translation, explanation, note, saved_to_card, created_at
FROM clippings
WHERE article_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListClippingsByArticle(ctx context.Context, articleID sql.NullString) ([]Clipping, error) {
	rows, err := q.db.QueryContext(ctx, listClippingsByArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clipping{}
	for rows.Next() {
		var i Clipping
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Text,
			&i.Translation,
			&i.Explanation,
			&i.Note,
			&i.SavedToCard,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :exec
UPDATE articles
SET title = ?, url = ?, content = ?, translation = ?, level = ?, word_count = ?, model_css = ?, raw_fields = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateArticleParams struct {
	Title       string `json:"title"`
	Url         string `json:"url"`
	Content     string `json:"content"`
	Translation string `json:"translation"`
	Level       string `json:"level"`
	WordCount   int64  `json:"word_count"`
	ModelCss    string `json:"model_css"`
	RawFields   string `json:"raw_fields"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) error {
	_, err := q.db.ExecContext(ctx, updateArticle,
		arg.Title,
		arg.Url,
		arg.Content,
		arg.Translation,
		arg.Level,
		arg.WordCount,
		arg.ModelCss,
		arg.RawFields,
		arg.ID,
	)
	return err
}

const updateClipping = `-- name: UpdateClipping :exec
UPDATE clippings
SET text = ?, translation = ?, explanation = ?, note = ?, saved_to_card = ?
WHERE id = ?
`

type UpdateClippingParams struct {
	Text        string `json:"text"`
	Translation string `json:"translation"`
	Explanation string `json:"explanation"`
	Note        string `json:"note"`
	SavedToCard int64  `json:"saved_to_card"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateClipping(ctx context.Context, arg UpdateClippingParams) error {
	_, err := q.db.ExecContext(ctx, updateClipping,
		arg.Text,
		arg.Translation,
		arg.Explanation,
		arg.Note,
		arg.SavedToCard,
		arg.ID,
	)
	return err
}
