// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"
)

const createChatMessage = `-- name: CreateChatMessage :exec
INSERT INTO chat_messages (id, session_id, role, content, created_at)
VALUES (?, ?, ?, ?, datetime('now'))
`

type CreateChatMessageParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) error {
	_, err := q.db.ExecContext(ctx, createChatMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Content,
	)
	return err
}

const createChatSession = `-- name: CreateChatSession :exec
INSERT INTO chat_sessions (id, title, created_at, updated_at)
VALUES (?, ?, datetime('now'), datetime('now'))
`

type CreateChatSessionParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) error {
	_, err := q.db.ExecContext(ctx, createChatSession, arg.ID, arg.Title)
	return err
}

const deleteChatSession = `-- name: DeleteChatSession :exec
DELETE FROM chat_sessions
WHERE id = ?
`

func (q *Queries) DeleteChatSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChatSession, id)
	return err
}

const getChatMessage = `-- name: GetChatMessage :one
SELECT id, session_id, role, content, created_at
FROM chat_messages
WHERE id = ?
`

func (q *Queries) GetChatMessage(ctx context.Context, id string) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, getChatMessage, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, title, created_at, updated_at
FROM chat_sessions
WHERE id = ?
`

func (q *Queries) GetChatSession(ctx context.Context, id string) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getChatSession, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, session_id, role, content, created_at
FROM chat_messages
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListChatMessages(ctx context.Context, sessionID string) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessions = `-- name: ListChatSessions :many
SELECT id, title, created_at, updated_at
FROM chat_sessions
ORDER BY updated_at DESC
`

func (q *Queries) ListChatSessions(ctx context.Context) ([]ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, listChatSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameChatSession = `-- name: RenameChatSession :exec
UPDATE chat_sessions
SET title = ?, updated_at = datetime('now')
WHERE id = ?
`

type RenameChatSessionParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) RenameChatSession(ctx context.Context, arg RenameChatSessionParams) error {
	_, err := q.db.ExecContext(ctx, renameChatSession, arg.Title, arg.ID)
	return err
}

const touchChatSession = `-- name: TouchChatSession :exec
UPDATE chat_sessions
SET updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) TouchChatSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchChatSession, id)
	return err
}
