// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: media.sql

package store

import (
	"context"
)

const createMediaAsset = `-- name: CreateMediaAsset :exec
INSERT INTO media_assets (id, original_filename, stored_path, mime_type, sha256, source, created_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateMediaAssetParams struct {
	ID               string `json:"id"`
	OriginalFilename string `json:"original_filename"`
	StoredPath       string `json:"stored_path"`
	MimeType         string `json:"mime_type"`
	Sha256           string `json:"sha256"`
	Source           string `json:"source"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) error {
	_, err := q.db.ExecContext(ctx, createMediaAsset,
		arg.ID,
		arg.OriginalFilename,
		arg.StoredPath,
		arg.MimeType,
		arg.Sha256,
		arg.Source,
	)
	return err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, original_filename, stored_path, mime_type, sha256, source, created_at
FROM media_assets
WHERE id = ?
`

func (q *Queries) GetMediaAsset(ctx context.Context, id string) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.StoredPath,
		&i.MimeType,
		&i.Sha256,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaAssetByFilename = `-- name: GetMediaAssetByFilename :one
SELECT id, original_filename, stored_path, mime_type, sha256, source, created_at
FROM media_assets
WHERE original_filename = ? AND source = ?
`

type GetMediaAssetByFilenameParams struct {
	OriginalFilename string `json:"original_filename"`
	Source           string `json:"source"`
}

func (q *Queries) GetMediaAssetByFilename(ctx context.Context, arg GetMediaAssetByFilenameParams) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAssetByFilename, arg.OriginalFilename, arg.Source)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.StoredPath,
		&i.MimeType,
		&i.Sha256,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaAssets = `-- name: ListMediaAssets :many
SELECT id, original_filename, stored_path, mime_type, sha256, source, created_at
FROM media_assets
WHERE source = ?
ORDER BY original_filename
`

func (q *Queries) ListMediaAssets(ctx context.Context, source string) ([]MediaAsset, error) {
	rows, err := q.db.QueryContext(ctx, listMediaAssets, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.StoredPath,
			&i.MimeType,
			&i.Sha256,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
