// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: srs.sql

package store

import (
	"context"
	"database/sql"
)

const countCardsByDeck = `-- name: CountCardsByDeck :one
SELECT COUNT(*) AS count
FROM cards
WHERE deck_id = ?
`

func (q *Queries) CountCardsByDeck(ctx context.Context, deckID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsByDeck, deckID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCard = `-- name: CreateCard :exec
INSERT INTO cards (
    id, deck_id, front, back, example_sentence, hints, card_type,
    ease, interval, repetitions, due_at, lapsed, suspended,
    source, anki_card_id, anki_note_guid, template_ord, model_css,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    datetime('now'), datetime('now')
)
`

type CreateCardParams struct {
	ID              string         `json:"id"`
	DeckID          string         `json:"deck_id"`
	Front           string         `json:"front"`
	Back            string         `json:"back"`
	ExampleSentence string         `json:"example_sentence"`
	Hints           string         `json:"hints"`
	CardType        string         `json:"card_type"`
	Ease            float64        `json:"ease"`
	Interval        int64          `json:"interval"`
	Repetitions     int64          `json:"repetitions"`
	DueAt           sql.NullString `json:"due_at"`
	Lapsed          int64          `json:"lapsed"`
	Suspended       int64          `json:"suspended"`
	Source          string         `json:"source"`
	AnkiCardID      sql.NullInt64  `json:"anki_card_id"`
	AnkiNoteGuid    sql.NullString `json:"anki_note_guid"`
	TemplateOrd     int64          `json:"template_ord"`
	ModelCss        string         `json:"model_css"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.ExecContext(ctx, createCard,
		arg.ID,
		arg.DeckID,
		arg.Front,
		arg.Back,
		arg.ExampleSentence,
		arg.Hints,
		arg.CardType,
		arg.Ease,
		arg.Interval,
		arg.Repetitions,
		arg.DueAt,
		arg.Lapsed,
		arg.Suspended,
		arg.Source,
		arg.AnkiCardID,
		arg.AnkiNoteGuid,
		arg.TemplateOrd,
		arg.ModelCss,
	)
	return err
}

const createDeck = `-- name: CreateDeck :exec
INSERT INTO decks (id, name, description, parent_id, sort_order, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type CreateDeckParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ParentID    sql.NullString `json:"parent_id"`
	SortOrder   int64          `json:"sort_order"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) error {
	_, err := q.db.ExecContext(ctx, createDeck,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.SortOrder,
	)
	return err
}

const createReviewLog = `-- name: CreateReviewLog :exec
INSERT INTO review_log (id, card_id, rating, elapsed_ms, review_at, day_seq, ease_before, interval_before)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReviewLogParams struct {
	ID             string          `json:"id"`
	CardID         string          `json:"card_id"`
	Rating         int64           `json:"rating"`
	ElapsedMs      int64           `json:"elapsed_ms"`
	ReviewAt       string          `json:"review_at"`
	DaySeq         int64           `json:"day_seq"`
	EaseBefore     sql.NullFloat64 `json:"ease_before"`
	IntervalBefore sql.NullInt64   `json:"interval_before"`
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) error {
	_, err := q.db.ExecContext(ctx, createReviewLog,
		arg.ID,
		arg.CardID,
		arg.Rating,
		arg.ElapsedMs,
		arg.ReviewAt,
		arg.DaySeq,
		arg.EaseBefore,
		arg.IntervalBefore,
	)
	return err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE id = ?
`

func (q *Queries) DeleteCard(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks
WHERE id = ?
`

func (q *Queries) DeleteDeck(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDeck, id)
	return err
}

const getCard = `-- name: GetCard :one
SELECT
    id, deck_id, front, back, example_sentence, hints, card_type,
    ease, interval, repetitions, due_at, lapsed, suspended,
    source, anki_card_id, anki_note_guid, template_ord, model_css,
    created_at, updated_at
FROM cards
WHERE id = ?
`

func (q *Queries) GetCard(ctx context.Context, id string) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.ExampleSentence,
		&i.Hints,
		&i.CardType,
		&i.Ease,
		&i.Interval,
		&i.Repetitions,
		&i.DueAt,
		&i.Lapsed,
		&i.Suspended,
		&i.Source,
		&i.AnkiCardID,
		&i.AnkiNoteGuid,
		&i.TemplateOrd,
		&i.ModelCss,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardByAnkiCardID = `-- name: GetCardByAnkiCardID :one
SELECT
    id, deck_id, front, back, example_sentence, hints, card_type,
    ease, interval, repetitions, due_at, lapsed, suspended,
    source, anki_card_id, anki_note_guid, template_ord, model_css,
    created_at, updated_at
FROM cards
WHERE anki_card_id = ?
`

func (q *Queries) GetCardByAnkiCardID(ctx context.Context, ankiCardID sql.NullInt64) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByAnkiCardID, ankiCardID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.ExampleSentence,
		&i.Hints,
		&i.CardType,
		&i.Ease,
		&i.Interval,
		&i.Repetitions,
		&i.DueAt,
		&i.Lapsed,
		&i.Suspended,
		&i.Source,
		&i.AnkiCardID,
		&i.AnkiNoteGuid,
		&i.TemplateOrd,
		&i.ModelCss,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeck = `-- name: GetDeck :one
SELECT id, name, description, parent_id, sort_order, created_at, updated_at
FROM decks
WHERE id = ?
`

func (q *Queries) GetDeck(ctx context.Context, id string) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByDeck = `-- name: ListCardsByDeck :many
SELECT
    id, deck_id, front, back, example_sentence, hints, card_type,
    ease, interval, repetitions, due_at, lapsed, suspended,
    source, anki_card_id, anki_note_guid, template_ord, model_css,
    created_at, updated_at
FROM cards
WHERE deck_id = ?
ORDER BY created_at
`

func (q *Queries) ListCardsByDeck(ctx context.Context, deckID string) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.ExampleSentence,
			&i.Hints,
			&i.CardType,
			&i.Ease,
			&i.Interval,
			&i.Repetitions,
			&i.DueAt,
			&i.Lapsed,
			&i.Suspended,
			&i.Source,
			&i.AnkiCardID,
			&i.AnkiNoteGuid,
			&i.TemplateOrd,
			&i.ModelCss,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildDecks = `-- name: ListChildDecks :many
SELECT id, name, description, parent_id, sort_order, created_at, updated_at
FROM decks
WHERE parent_id = ?
ORDER BY sort_order, name
`

func (q *Queries) ListChildDecks(ctx context.Context, parentID sql.NullString) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listChildDecks, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecks = `-- name: ListDecks :many
SELECT id, name, description, parent_id, sort_order, created_at, updated_at
FROM decks
ORDER BY sort_order, name
`

func (q *Queries) ListDecks(ctx context.Context) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, listDecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deck{}
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCards = `-- name: ListDueCards :many
SELECT
    id, deck_id, front, back, example_sentence, hints, card_type,
    ease, interval, repetitions, due_at, lapsed, suspended,
    source, anki_card_id, anki_note_guid, template_ord, model_css,
    created_at, updated_at
FROM cards
WHERE deck_id = ?
  AND suspended = 0
  AND due_at IS NOT NULL
  AND due_at <= ?
ORDER BY due_at
LIMIT ?
`

type ListDueCardsParams struct {
	DeckID string         `json:"deck_id"`
	DueAt  sql.NullString `json:"due_at"`
	Limit  int64          `json:"limit"`
}

func (q *Queries) ListDueCards(ctx context.Context, arg ListDueCardsParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listDueCards, arg.DeckID, arg.DueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.ExampleSentence,
			&i.Hints,
			&i.CardType,
			&i.Ease,
			&i.Interval,
			&i.Repetitions,
			&i.DueAt,
			&i.Lapsed,
			&i.Suspended,
			&i.Source,
			&i.AnkiCardID,
			&i.AnkiNoteGuid,
			&i.TemplateOrd,
			&i.ModelCss,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewCards = `-- name: ListNewCards :many
SELECT
    id, deck_id, front, back, example_sentence, hints, card_type,
    ease, interval, repetitions, due_at, lapsed, suspended,
    source, anki_card_id, anki_note_guid, template_ord, model_css,
    created_at, updated_at
FROM cards
WHERE deck_id = ?
  AND suspended = 0
  AND due_at IS NULL
ORDER BY created_at
LIMIT ?
`

type ListNewCardsParams struct {
	DeckID string `json:"deck_id"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListNewCards(ctx context.Context, arg ListNewCardsParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listNewCards, arg.DeckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.ExampleSentence,
			&i.Hints,
			&i.CardType,
			&i.Ease,
			&i.Interval,
			&i.Repetitions,
			&i.DueAt,
			&i.Lapsed,
			&i.Suspended,
			&i.Source,
			&i.AnkiCardID,
			&i.AnkiNoteGuid,
			&i.TemplateOrd,
			&i.ModelCss,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewLogByCard = `-- name: ListReviewLogByCard :many
SELECT id, card_id, rating, elapsed_ms, review_at, day_seq, ease_before, interval_before
FROM review_log
WHERE card_id = ?
ORDER BY review_at DESC
`

func (q *Queries) ListReviewLogByCard(ctx context.Context, cardID string) ([]ReviewLog, error) {
	rows, err := q.db.QueryContext(ctx, listReviewLogByCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewLog{}
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Rating,
			&i.ElapsedMs,
			&i.ReviewAt,
			&i.DaySeq,
			&i.EaseBefore,
			&i.IntervalBefore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardContent = `-- name: UpdateCardContent :exec
UPDATE cards
SET front = ?, back = ?, example_sentence = ?, hints = ?, card_type = ?, model_css = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateCardContentParams struct {
	Front           string `json:"front"`
	Back            string `json:"back"`
	ExampleSentence string `json:"example_sentence"`
	Hints           string `json:"hints"`
	CardType        string `json:"card_type"`
	ModelCss        string `json:"model_css"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateCardContent(ctx context.Context, arg UpdateCardContentParams) error {
	_, err := q.db.ExecContext(ctx, updateCardContent,
		arg.Front,
		arg.Back,
		arg.ExampleSentence,
		arg.Hints,
		arg.CardType,
		arg.ModelCss,
		arg.ID,
	)
	return err
}

const updateCardSRS = `-- name: UpdateCardSRS :exec
UPDATE cards
SET ease = ?, interval = ?, repetitions = ?, due_at = ?, lapsed = ?, suspended = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateCardSRSParams struct {
	Ease        float64        `json:"ease"`
	Interval    int64          `json:"interval"`
	Repetitions int64          `json:"repetitions"`
	DueAt       sql.NullString `json:"due_at"`
	Lapsed      int64          `json:"lapsed"`
	Suspended   int64          `json:"suspended"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateCardSRS(ctx context.Context, arg UpdateCardSRSParams) error {
	_, err := q.db.ExecContext(ctx, updateCardSRS,
		arg.Ease,
		arg.Interval,
		arg.Repetitions,
		arg.DueAt,
		arg.Lapsed,
		arg.Suspended,
		arg.ID,
	)
	return err
}

const updateDeck = `-- name: UpdateDeck :exec
UPDATE decks
SET name = ?, description = ?, parent_id = ?, sort_order = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateDeckParams struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	ParentID    sql.NullString `json:"parent_id"`
	SortOrder   int64          `json:"sort_order"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) error {
	_, err := q.db.ExecContext(ctx, updateDeck,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.SortOrder,
		arg.ID,
	)
	return err
}
