// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package store

import (
	"context"
)

const deleteAllUserAccounts = `-- name: DeleteAllUserAccounts :exec
DELETE FROM user_account
`

func (q *Queries) DeleteAllUserAccounts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserAccounts)
	return err
}

const getCurrentUser = `-- name: GetCurrentUser :one
SELECT id, provider, provider_user_id, display_name, email, avatar_url, created_at, last_login_at
FROM user_account
ORDER BY last_login_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentUser(ctx context.Context) (UserAccount, error) {
	row := q.db.QueryRowContext(ctx, getCurrentUser)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.DisplayName,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertUserAccount = `-- name: InsertUserAccount :exec
INSERT INTO user_account (
    id,
    provider,
    provider_user_id,
    display_name,
    email,
    avatar_url,
    created_at,
    last_login_at
)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type InsertUserAccountParams struct {
	ID             string `json:"id"`
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
	DisplayName    string `json:"display_name"`
	Email          string `json:"email"`
	AvatarUrl      string `json:"avatar_url"`
}

func (q *Queries) InsertUserAccount(ctx context.Context, arg InsertUserAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertUserAccount,
		arg.ID,
		arg.Provider,
		arg.ProviderUserID,
		arg.DisplayName,
		arg.Email,
		arg.AvatarUrl,
	)
	return err
}
