// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary.sql

package store

import (
	"context"
	"database/sql"
)

const createVocabulary = `-- name: CreateVocabulary :exec
INSERT INTO vocabulary (
    id, word, phonetic, pos, definition, definition_en, examples, level, source, anki_note_guid, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
`

type CreateVocabularyParams struct {
	ID           string         `json:"id"`
	Word         string         `json:"word"`
	Phonetic     string         `json:"phonetic"`
	Pos          string         `json:"pos"`
	Definition   string         `json:"definition"`
	DefinitionEn string         `json:"definition_en"`
	Examples     string         `json:"examples"`
	Level        string         `json:"level"`
	Source       string         `json:"source"`
	AnkiNoteGuid sql.NullString `json:"anki_note_guid"`
}

func (q *Queries) CreateVocabulary(ctx context.Context, arg CreateVocabularyParams) error {
	_, err := q.db.ExecContext(ctx, createVocabulary,
		arg.ID,
		arg.Word,
		arg.Phonetic,
		arg.Pos,
		arg.Definition,
		arg.DefinitionEn,
		arg.Examples,
		arg.Level,
		arg.Source,
		arg.AnkiNoteGuid,
	)
	return err
}

const deleteVocabulary = `-- name: DeleteVocabulary :exec
DELETE FROM vocabulary
WHERE id = ?
`

func (q *Queries) DeleteVocabulary(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVocabulary, id)
	return err
}

const getVocabulary = `-- name: GetVocabulary :one
SELECT id, word, phonetic, pos, definition, definition_en, examples, level, source, anki_note_guid, created_at
FROM vocabulary
WHERE id = ?
`

func (q *Queries) GetVocabulary(ctx context.Context, id string) (Vocabulary, error) {
	row := q.db.QueryRowContext(ctx, getVocabulary, id)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Phonetic,
		&i.Pos,
		&i.Definition,
		&i.DefinitionEn,
		&i.Examples,
		&i.Level,
		&i.Source,
		&i.AnkiNoteGuid,
		&i.CreatedAt,
	)
	return i, err
}

const getVocabularyByAnkiNoteGuid = `-- name: GetVocabularyByAnkiNoteGuid :one
SELECT id, word, phonetic, pos, definition, definition_en, examples, level, source, anki_note_guid, created_at
FROM vocabulary
WHERE anki_note_guid = ?
`

func (q *Queries) GetVocabularyByAnkiNoteGuid(ctx context.Context, ankiNoteGuid sql.NullString) (Vocabulary, error) {
	row := q.db.QueryRowContext(ctx, getVocabularyByAnkiNoteGuid, ankiNoteGuid)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Phonetic,
		&i.Pos,
		&i.Definition,
		&i.DefinitionEn,
		&i.Examples,
		&i.Level,
		&i.Source,
		&i.AnkiNoteGuid,
		&i.CreatedAt,
	)
	return i, err
}

const linkCardVocab = `-- name: LinkCardVocab :exec
INSERT INTO card_vocab (card_id, vocab_id)
VALUES (?, ?)
ON CONFLICT(card_id, vocab_id) DO NOTHING
`

type LinkCardVocabParams struct {
	CardID  string `json:"card_id"`
	VocabID string `json:"vocab_id"`
}

func (q *Queries) LinkCardVocab(ctx context.Context, arg LinkCardVocabParams) error {
	_, err := q.db.ExecContext(ctx, linkCardVocab, arg.CardID, arg.VocabID)
	return err
}

const listCardsForVocab = `-- name: ListCardsForVocab :many
SELECT
    c.id, c.deck_id, c.front, c.back, c.example_sentence, c.hints, c.card_type,
    c.ease, c.interval, c.repetitions, c.due_at, c.lapsed, c.suspended,
    c.source, c.anki_card_id, c.anki_note_guid, c.template_ord, c.model_css,
    c.created_at, c.updated_at
FROM cards c
INNER JOIN card_vocab cv ON cv.card_id = c.id
WHERE cv.vocab_id = ?
ORDER BY c.created_at
`

func (q *Queries) ListCardsForVocab(ctx context.Context, vocabID string) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsForVocab, vocabID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.ExampleSentence,
			&i.Hints,
			&i.CardType,
			&i.Ease,
			&i.Interval,
			&i.Repetitions,
			&i.DueAt,
			&i.Lapsed,
			&i.Suspended,
			&i.Source,
			&i.AnkiCardID,
			&i.AnkiNoteGuid,
			&i.TemplateOrd,
			&i.ModelCss,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabForCard = `-- name: ListVocabForCard :many
SELECT v.id, v.word, v.phonetic, v.pos, v.definition, v.definition_en, v.examples, v.level, v.source, v.anki_note_guid, v.created_at
FROM vocabulary v
INNER JOIN card_vocab cv ON cv.vocab_id = v.id
WHERE cv.card_id = ?
ORDER BY v.word
`

func (q *Queries) ListVocabForCard(ctx context.Context, cardID string) ([]Vocabulary, error) {
	rows, err := q.db.QueryContext(ctx, listVocabForCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vocabulary{}
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Phonetic,
			&i.Pos,
			&i.Definition,
			&i.DefinitionEn,
			&i.Examples,
			&i.Level,
			&i.Source,
			&i.AnkiNoteGuid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabulary = `-- name: ListVocabulary :many
SELECT id, word, phonetic, pos, definition, definition_en, examples, level, source, anki_note_guid, created_at
FROM vocabulary
ORDER BY word
`

func (q *Queries) ListVocabulary(ctx context.Context) ([]Vocabulary, error) {
	rows, err := q.db.QueryContext(ctx, listVocabulary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vocabulary{}
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Phonetic,
			&i.Pos,
			&i.Definition,
			&i.DefinitionEn,
			&i.Examples,
			&i.Level,
			&i.Source,
			&i.AnkiNoteGuid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyByLevel = `-- name: ListVocabularyByLevel :many
SELECT id, word, phonetic, pos, definition, definition_en, examples, level, source, anki_note_guid, created_at
FROM vocabulary
WHERE level = ?
ORDER BY word
`

func (q *Queries) ListVocabularyByLevel(ctx context.Context, level string) ([]Vocabulary, error) {
	rows, err := q.db.QueryContext(ctx, listVocabularyByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vocabulary{}
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Phonetic,
			&i.Pos,
			&i.Definition,
			&i.DefinitionEn,
			&i.Examples,
			&i.Level,
			&i.Source,
			&i.AnkiNoteGuid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVocabulary = `-- name: SearchVocabulary :many
SELECT id, word, phonetic, pos, definition, definition_en, examples, level, source, anki_note_guid, created_at
FROM vocabulary
WHERE word LIKE '%' || ? || '%'
   OR definition LIKE '%' || ? || '%'
ORDER BY word
LIMIT ?
`

type SearchVocabularyParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchVocabulary(ctx context.Context, arg SearchVocabularyParams) ([]Vocabulary, error) {
	rows, err := q.db.QueryContext(ctx, searchVocabulary, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vocabulary{}
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.Word,
			&i.Phonetic,
			&i.Pos,
			&i.Definition,
			&i.DefinitionEn,
			&i.Examples,
			&i.Level,
			&i.Source,
			&i.AnkiNoteGuid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVocabulary = `-- name: UpdateVocabulary :exec
UPDATE vocabulary
SET word = ?, phonetic = ?, pos = ?, definition = ?, definition_en = ?, examples = ?, level = ?, source = ?
WHERE id = ?
`

type UpdateVocabularyParams struct {
	Word         string `json:"word"`
	Phonetic     string `json:"phonetic"`
	Pos          string `json:"pos"`
	Definition   string `json:"definition"`
	DefinitionEn string `json:"definition_en"`
	Examples     string `json:"examples"`
	Level        string `json:"level"`
	Source       string `json:"source"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateVocabulary(ctx context.Context, arg UpdateVocabularyParams) error {
	_, err := q.db.ExecContext(ctx, updateVocabulary,
		arg.Word,
		arg.Phonetic,
		arg.Pos,
		arg.Definition,
		arg.DefinitionEn,
		arg.Examples,
		arg.Level,
		arg.Source,
		arg.ID,
	)
	return err
}
